// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

X( TextureNode, "TextureNode" )
X( AddNode, "AddNode" )
X( SubtractNode, "SubtractNode" )
X( MultiplyNode, "MultiplyNode" )
X( DivideNode, "DivideNode" )
X( VertexColorNode, "VertexColorNode" )
X( SwizzlingNode, "SwizzlingNode" )
X( InterpolateNode, "InterpolateNode" )
X( CustomNode, "CustomNode" )
X( ClampNode, "ClampNode" )
X( ColorNode, "ColorNode" )
X( LayeredBlendNode, "LayeredBlendNode" )
X( PowNode, "PowNode" )
X( Normalize3Node, "Normalize3Node" )
X( SqrtNode, "SqrtNode" )
X( Dot3Node, "Dot3Node" )
X( Cross3Node, "Cross3Node" )
X( CosNode, "CosNode" )
X( SinNode, "SinNode" )
X( MaxNode, "MaxNode" )
X( MinNode, "MinNode" )
X( EqualNode, "EqualNode" )
X( NotEqualNode, "NotEqualNode" )
X( GreaterThanNode, "GreaterThanNode" )
X( LessThanNode, "LessThanNode" )
X( GeometryFieldNode, "GeometryFieldNode" )
X( Undefined, "Undefined" )